name: amld20_img_clf
channels:
  - conda-forge
  - defaults
dependencies:
  - imageio
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pip
  - python
  - scikit-learn
  - scipy
  - seaborn
  - tqdm
  - pip:
    - google-images-download
    - tensorflow==2.1
    - tensorflow-hub
