name: amld20_img_clf
channels:
  - conda-forge
  - defaults
dependencies:
  - imageio=2.5.0
  - joblib=0.13.2
  - jupyterlab
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - matplotlib-base=3.1.2
  - notebook=6.0.1
  - numpy=1.17.0
  - pandas=0.25.1
  - pip=19.2.2
  - python=3.7
  - scikit-learn=0.22
  - scipy=1.3.1
  - seaborn=0.9.0
  - setuptools=41.2.0
  - six=1.12.0
  - statsmodels=0.10.1
  - tensorflow-base=2.0.0
  - tensorflow-estimator=2.0.0
  - pip:
    - google-images-download==2.8.0
    - h5py==2.9.0
    - matplotlib==3.1.0
    - opencv-python==4.1.0.25
    - requests==2.22
    - scikit-image==0.15.0
    - tb-nightly==1.15
    - tensorboard==1.14.0
    - tensorflow-datasets==1.2.0
    - tensorflow-hub==0.5.0
    - tensorflow-metadata==0.14.0
    - tensorflow-probability==0.8.0
    - tensorflow==2.0.0rc0
    - tf-estimator-nightly==1.14.0