name: amld20_img_clf
channels:
  - conda-forge
  - defaults
dependencies:
  - imageio=2.5
  - ipython=7.7
  - joblib=0.13
  - jupyterlab
  - numpy=1.17
  - pandas=0.25
  - pip
  - python=3.7
  - scikit-learn=0.22
  - scipy=1.3
  - seaborn=0.9
  - pip:
    - google-images-download==2.8
    - matplotlib==3.1
    - requests==2.22
    - tensorflow==2
    - tensorflow-hub==0.5
